# Generated by Django 3.2.8 on 2021-10-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('list_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('picture_url', models.URLField()),
                ('user_priority', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'Item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('list_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'List',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
