version: "3.9"
   
services:
  db:
    image: mysql
    environment:
       MYSQL_DATABASE: 'v2liihwo9uco38ul'
       MYSQL_USER: 'yiakr1drv9hh1emx'
       MYSQL_PASSWORD: 'llbtbi48zdzksa70'
       MYSQL_ROOT_PASSWORD: '438groupn'
    expose:
      - '3306'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/cst438project02
    ports:
      - "8888:8888"
    depends_on:
      - db


